##this particular test has been generated by AI to test filter_embedded_documents() of embeddings.py and then modified to fit the purpose
from retrieval import retrieve_all_samples
from document import samples_to_text
from embeddings import (
    get_embeddings, 
    filter_embedded_documents,
    EMBEDDING_FILE
)

samples = retrieve_all_samples()

documents = samples_to_text(samples)
embedded_documents = get_embeddings(documents)


def print_results(name, results):

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    print("Number of results:", len(results))

    for document in results[:5]:
        print(
            document["uid"],
            "| Peptide:", document["metadata"]["peptide_name"],
            "| HAuCl4:", document["metadata"]["haucl4"],
            "| HEPES:", document["metadata"]["hepes"]
        )


# --------------------------------------------------
# 1. No filter -> all documents
# --------------------------------------------------

results = filter_embedded_documents(
    embedded_documents,
    []
)

print_results(
    "NO FILTER",
    results
)

assert len(results) == len(embedded_documents)


# --------------------------------------------------
# 2. Equality
# peptide_name = PZ2
# --------------------------------------------------

filters = [
    {
        "field": "peptide_name",
        "operator": "=",
        "value": "PZ2"
    }
]

results = filter_embedded_documents(
    embedded_documents,
    filters
)

print_results(
    "peptide_name = PZ2",
    results
)

assert all(
    document["metadata"]["peptide_name"] == "PZ2"
    for document in results
)


# --------------------------------------------------
# 3. NOT EQUAL
# peptide_name != PZ2
# --------------------------------------------------

filters = [
    {
        "field": "peptide_name",
        "operator": "!=",
        "value": "PZ2"
    }
]

results = filter_embedded_documents(
    embedded_documents,
    filters
)

print_results(
    "peptide_name != PZ2",
    results
)

assert all(
    document["metadata"]["peptide_name"] != "PZ2"
    for document in results
)


# --------------------------------------------------
# 4. IN
# PZ2 or MZ2R
# --------------------------------------------------

filters = [
    {
        "field": "peptide_name",
        "operator": "IN",
        "value": ["PZ2", "MZ2R"]
    }
]

results = filter_embedded_documents(
    embedded_documents,
    filters
)

print_results(
    "peptide_name IN [PZ2, MZ2R]",
    results
)

assert all(
    document["metadata"]["peptide_name"] in ["PZ2", "MZ2R"]
    for document in results
)


# --------------------------------------------------
# 5. NOT IN
# --------------------------------------------------

filters = [
    {
        "field": "peptide_name",
        "operator": "NOT IN",
        "value": ["PZ2", "MZ2R"]
    }
]

results = filter_embedded_documents(
    embedded_documents,
    filters
)

print_results(
    "peptide_name NOT IN [PZ2, MZ2R]",
    results
)

assert all(
    document["metadata"]["peptide_name"] not in ["PZ2", "MZ2R"]
    for document in results
)


# --------------------------------------------------
# 6. HAuCl4 <
# --------------------------------------------------

filters = [
    {
        "field": "haucl4",
        "operator": "<",
        "value": 0.0001
    }
]

results = filter_embedded_documents(
    embedded_documents,
    filters
)

print_results(
    "HAuCl4 < 0.0001",
    results
)

assert all(
    document["metadata"]["haucl4"] < 0.0001
    for document in results
)


# --------------------------------------------------
# 7. HAuCl4 >
# --------------------------------------------------

filters = [
    {
        "field": "haucl4",
        "operator": ">",
        "value": 0.0001
    }
]

results = filter_embedded_documents(
    embedded_documents,
    filters
)

print_results(
    "HAuCl4 > 0.0001",
    results
)

assert all(
    document["metadata"]["haucl4"] > 0.0001
    for document in results
)


# --------------------------------------------------
# 8. Multiple filters
# PZ2 AND HAuCl4 < 0.0001
# --------------------------------------------------

filters = [
    {
        "field": "peptide_name",
        "operator": "=",
        "value": "PZ2"
    },
    {
        "field": "haucl4",
        "operator": "<",
        "value": 0.0001
    }
]

results = filter_embedded_documents(
    embedded_documents,
    filters
)

print_results(
    "PZ2 AND HAuCl4 < 0.0001",
    results
)

assert all(
    document["metadata"]["peptide_name"] == "PZ2"
    and document["metadata"]["haucl4"] < 0.0001
    for document in results
)


print("\nAll tests passed!")